name: automaat_app
description: "Mobile app developed for 'mobile app development' course"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  http: ^1.2.2
  dio: ^5.7.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  flutter_cache_manager: ^3.4.1
  floor: ^1.4.2
  sqflite: ^2.4.1
  vector_graphics: ^1.1.15
  intl: ^0.20.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2
  connectivity_plus: ^6.1.2
  internet_connection_checker_plus: ^2.7.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  floor_generator: ^1.4.2
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.14
  vector_graphics_compiler: ^1.1.16

flutter:
  uses-material-design: true

  assets:
    - assets/logo_foreground.png
    - assets/logo.png
    - assets/automaat_logo_purple.svg
    - assets/automaat_logo_purple.svg.vec
    - assets/automaat_logo_white.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#FFFFFF"